### ISSUE TITLE
[Bug] always generate paths with forward slashes in consistency checks

### ISSUE THREAD

**Issue by NikkyAI** [krzema12/github-actions-kotlin-dsl#67]
seems like when you generate the yaml on windows (kotlin installed via scoop)
the cosistency check uses backslashes and will fail in CI

**Comment by krzema12** [comment]
I'm considering a simple solution: make `sourceFile` and `targetFile` plain strings instead of `Path`s.  It's a breaking change, but IMO not a problem in such early age of the lib. Thanks to this, the consistency check would contain exactly what is given in the string, and there would be no OS-specific logic involved.

**Comment by krzema12** [comment]
@NikkyAI could you run the code from this PR on your Windows machine and confirm it works fine? #68

**Comment by NikkyAI** [comment]
can you give me some hints for how to run this when its not packaged as maven artifact ?
otherwise i will do this tomorrow when i have to to check out the repo and run the tests

apart from that.. if it does not break anything on linux then chances are it would not be worse on windows either..

**Comment by NikkyAI** [comment]
its fixed
